name: Full Stack CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          python main.py test


  frontend:
    runs-on: ubuntu-latest
  
    defaults:
      run:
        working-directory: frontend/vite-project
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
  
      - name: Install dependencies
        run: npm install
  
      - name: Build project
        run: npm run build
